export const ADD_MOVIE = 'ADD_MOVIE'
export const REMOVE_MOVIE = 'REMOVE_MOVIE'
export const SHOW_ALL = 'SHOW_ALL'
export const SHOW_TITLE = 'SHOW_TITLE'
 export const EDIT_MOVIE = "EDIT_MOVIE";
// export const CLOSE_FORM = "CLOSE_FORM";
// export const OPEN_EDIT_FORM = "OPEN_EDIT_FORM";
// export const CLOSE_EDIT_FORM = "CLOSE_EDIT_FORM";
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER'